### ISSUE TITLE
imdb 웹사이트 외부링크로 연결하기

### ISSUE THREAD

**Issue by gonasooc** [udemy-team13/react-movie#4]
디테일 페이지

- [x] imdb값 확인하기
- [x] https://www.imdb.com/title/${ibdb}/
- [x] a 태그의 target attribute 선언해서 새 창으로 띄어주는 게 좋을 듯(참고 페이지 확인)
- https://yts.mx/movies/kisi-ka-bhai-kisi-ki-jaan-2023

**Comment by nanhimang** [comment]
fetch된 data에 [url] key 값으로 가꼬오면 되네용

**Comment by nanhimang** [comment]
다했어염!
